name: Commit Messages on Push

on:
  push:
    branches:
      - test
env:
  ALL_MESSAGE: ""

jobs:
  get_commit_messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit messages
        run: |
          echo '${{ toJSON(github.event.commits) }}' | jq ".[0].message"
          
          array=${{ github.event.commits }}
          
          echo $(jq length <<< '${{ toJSON(github.event.commits) }}')
          
          for (( i = 0; i < ${#array[@]}; i++ )); do
            echo '${{ toJSON(github.event.commits) }}' | jq ".[$i].message"
            echo $i
          done
