name: Commit Messages on Push

on:
  push:
    branches:
      - test

jobs:
  get_commit_messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit messages
        run: |
          echo ${{ github.event.head_commit.message }}
          echo ${{ github.event.commits[0].message }}
          echo ${{ github.event.commits[1].message }}
          echo ${{ github.event.commits[2].message }}
          
          testArray = ${{ github.event.commits }}
          
          for a in ${testArray[@]}
          do
            echo ${a[message]}
          done
