name: Pull request comment
on:
  issue_comment:
    types: [created, edited]
jobs:
  pull_request_comment:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'release-')
    runs-on: ubuntu-latest
    
    steps:
      - name: 실행!
        if: contains(github.event.comment.body, 'batch')
        run: |
          echo ${{ github.event.comment.body }}
          echo "batch Done"
        
      - name: 실행!
        if: contains(github.event.comment.body, 'userapi')
        run: |
          echo ${{ github.event.comment.body }}
          echo "userapi Done"
