name: Commit Messages on Push

on:
  push:
    branches:
      - test

jobs:
  get_commit_messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit messages
        run: |
          
          array=${{ github.event.commits }}
          
          echo "============================="
          echo ${#array[@]}
          echo "============================="
          
          # Loop through all commits and print their messages
          for commit in ${{ toJson(github.event.commits) }}; do
            message=$(echo "$commit" | jq -r '.message')
            echo "Commit Message: $message"
          done
