name: Commit Messages on Push

on:
  push:
    branches:
      - test

jobs:
  get_commit_messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit messages
        run: |
          # Get the latest commit SHA
          LAST_COMMIT_SHA=$GITHUB_SHA

          # Get the SHA of the commit before the last one
          PARENT_COMMIT_SHA=$(git rev-parse $LAST_COMMIT_SHA^)

          # Get the commit messages between the parent and last commit
          COMMIT_MESSAGES=$(git log --format=%B $PARENT_COMMIT_SHA..$LAST_COMMIT_SHA)

          # Loop through each commit message and print it
          while IFS= read -r commit_message; do
            echo "Commit message: $commit_message"
          done <<< "$COMMIT_MESSAGES"
