name: Commit Messages on Push

on:
  push:
    branches:
      - test
env:
  ALL_MESSAGE: ""

jobs:
  get_commit_messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit messages
        run: |
          echo ${{ github.event.head_commit.message }}
          echo ${{ github.event.commits[0].author.name }}
          echo ${{ github.event.commits[0].message }}
          echo ${{ github.event.commits[1].author.name }}
          echo ${{ github.event.commits[1].message }}
          echo ${{ github.event.commits[2].author.name }}
          echo ${{ github.event.commits[2].message }}
          echo ${{ github.event.commits.message }}
          
          array=${{ github.event.commits }}
          
          echo "============================="
          echo ${#array[@]}
          echo "============================="
          
          for commit in ${{ github.event.commits }}; do
            test=$commit
            echo ${test[message]}
          done
          
      - uses: actions/github-script@v6
        with:
          script: |
            const commits = ${{ toJSON(github.event.commits) }}
            for (const commit of commits) {
            
            }
