name: Commit Messages on Push

on:
  push:
    branches:
      - test

jobs:
  get_commit_messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit messages
        run: |
          echo ${{ github.event.head_commit.message }}
          echo ${{ github.evnet.commits[0].message }}
          echo ${{ github.evnet.commits[1].message }}
          echo ${{ github.evnet.commits[2].message }}
