name: Commit Messages on Push

on:
  push:
    branches:
      - test
env:
  ALL_MESSAGE: ""

jobs:
  get_commit_messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit messages
        run: |
          echo '${{ toJSON(github.event.commits) }}' | jq ".[0].message"
          
          length=$(jq length <<< '${{ toJSON(github.event.commits) }}')
          
          for (( i = 0; i < $length; i++ )); do
            commit="'${{ toJSON(github.event.commits) }}' | jq ".[$i].message""
            echo $commit
          done
          
          echo $ALL_MESSAGE
