name: Pull request comment
on:
  issue_comment:
    types: [created, edited]
jobs:
  pull_request_comment:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'release-')
    runs-on: ubuntu-latest
    
    steps:
      - name: 실행!
        if: contains(github.event.comment.body, 'batch')
        run: |
          echo ${{ github.event.comment.body }}
          echo "batch Done"
        
      - name: 실행!
        if: contains(github.event.comment.body, 'userapi')
        run: |
          echo ${{ github.event.comment.body }}
          echo "userapi Done"
      - name: Fetch PR information
        run: |
          PR_NUMBER=$(jq -r ".pull_request.number" "$GITHUB_EVENT_PATH")
          PR_COMMITS=$(curl -s "https://api.github.com/repos/pcjin22/Github_Action_TEST/pull/1/commits" -H "Authorization: Bearer ${{ secrets.SECRET_TOKEN }}" | jq -r ".[].sha")
          echo "Commits in the PR: $PR_COMMITS"
