name: Commit Messages on Push

on:
  push:
    branches:
      - test
env:
  ALL_MESSAGE: ""

jobs:
  get_commit_messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit messages
        run: |
          echo '${{ toJSON(github.event.commits) }}' | jq ".[0].message"
          
          length=$(jq length <<< '${{ toJSON(github.event.commits) }}')
          
          for commit in ${{ toJSON(github.event.commits) }}; do
            message=$(jq -r '.message' <<< "$commit")
            messages="${messages}\n- $message"
          done
